apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: drone


helmCharts:
- name: drone-server
  includeCRDs: true
  repo: https://charts.cryptic.systems/volker.raschek
  version: 0.3.1
  releaseName: drone
  # override with these custom values
  valuesFile: values.yaml