apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: drone-io

# Bitnami NGINX helm chart
helmChartInflationGenerator:
- chartName: drone
  chartRepoUrl: https://charts.cryptic.systems/volker.raschek
  chartVersion: 0.3.0
  releaseName: drone
  releaseNamespace: drone-io
  # override with these custom values
  values: values.yaml