apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - namespace.yaml
namespace: drone


helmCharts:
- name: drone-runner
  includeCRDs: true
  repo: https://charts.cryptic.systems/volker.raschek
  version: 0.5.0
  releaseName: drone-runner
  # override with these custom values
  valuesFile: values.yaml